services:
  caddy-setup:
    networks:
      - proxy
    image: pknw1/setup.pknw1.co.uk:latest
    container_name: caddy-setup
    hostname: caddy-setup
    environment:
      - VIRTUAL_HOST=setup.pknw1.co.uk
      - VIRTUAL_PORT=80


networks:
  proxy:
    external: true

